language: node_js
node_js: 
  - "8.9.4"
cache:
  directories:
    - node_modules
branches:
  only:
    - master
before_script:
  - yarn global add firebase-tools
  - yarn global add @angular/cli
script:
  - yarn prod-build
after_success:
  - firebase deploy --token $FIREBASE_TOKEN